### ISSUE TITLE
python support in elinks : python2 ? python3 ?

### ISSUE THREAD

**Issue by m040601** [hellricer/soupmonkey#8]
Very interesting project.

> https://hellricer.github.io/2019/05/29/elinks-with-beautifulsoup.html
> *Note: ELinks in my Debian was missing the Python support. You might have to compile it from the source, if that's the case for your distribution as well.
> 

> https://hellricer.github.io/2019/10/04/modify-dom-in-elinks-with-soupmonkey.html
> Note: The latest elinks package in Debian is missing the Python support. You might have to build it with python support manually, if that's the case for your distribution as well.
> 

Could you confirm under which Linux distribution are you actually using this ? Was it Debian ? Stable ?
Are you using a packaged elinks version or one that you compiled yourself ? How did you manage to compile it ? How did you manage to do it ? Was it with python2 or python3 ? Could you clarify which python support is in fact needed ? 

I was trying to test it but had no success, because my standard elinks version on ArchLinux doesnt seem to support python

> ELinks 0.13.GIT 25c2850b597ee9a89bda8920e7f3d65ac3ac7e01-dirty
> Built on Jan  6 2019 18:10:15
> 
> Features:
> Standard, IPv6, gzip, bzip2, UTF-8, Periodic Saving, Viewer (Search
> History, Timer, Marks), Cascading Style Sheets, Protocol
> (Authentication, File, CGI, FTP, HTTP, URI rewrite, User protocols),
> SSL (OpenSSL), MIME (Option system, Mailcap, Mimetypes files), LED
> indicators, Bookmarks, Cookies, Form History, Global History, Scripting
> (Lua), Goto URL History

So I tried to compile a custom elinks version supporting Python. But we are not getting very lucky in ArchLinux:

> https://aur.archlinux.org/packages/elinks-git/#comment-721941
> 
>  ....wasn't able to make python work. It also seems to only support python2, which is not supported any more by 2020.....
> .....The Python support is incomplete and not so well integrated to ELinks yet. ...
> ...Which yet again gives me the impression that this is not a stable feature.
> ...In conclusion this feature sadly seems to be not well supported,....

Another possibilty I wanted to ask.
I was wondering in case one's elinks version doesnt support python and only supports Lua scripts. Would it be possible to "call" these python scripts from some sort of lua code/hook ? Python readability/lxml/beautsoup would do it's work independently of elinks and the Lua would act as a "glue" code.

**Comment by 0lOI0lOI000I0l0IOIlOl0l0ll0IllI0l00OIO0** [comment]
Hi,

From what I have seen most distros do not compile elinks with python support.

Elinks, as of now, can only by compiled with python2.

I have a modified PKGBUILD (below) I use to compile elinks with python features (along with perl and spidermonkey features). Run `makepkg` as follows to ensure you use python2:

`CPATH=/usr/include/python2.7/ PYTHON=/usr/bin/python2.7 makepkg -srief`

PKGBUILD:

```

# Contributor: Kyle Keen <keenerd@gmail.com>
# Contributor: Sergej Pupykin <pupykin.s+arch@gmail.com>
# Contributor: Andrea Scarpino <andrea@archlinux.org>
# Contributor: damir <damir@archlinux.org>
# Contributor: Ben <contrasutra@myrealbox.com>
# Maintainer: ferreum <code.danielk at gmail com>

_pkgname=elinks
pkgname=${_pkgname}-git
pkgver=0.13.1481.rf86be659
pkgrel=1
pkgdesc="An advanced and well-established feature-rich text mode web browser. Git version."
arch=("i686" "x86_64")
url="http://elinks.or.cz"
provides=(${_pkgname})
license=('GPL')
conflicts=(${_pkgname})
depends=('bzip2' 'expat>=2.0' 'gpm>=1.20.4' 'openssl' 'lua51' 'libidn' 'js185' 'gc' 'tre' 'python2')
source=("git+http://elinks.cz/elinks.git"
        "lua_strlen_fix.patch")
md5sums=('SKIP'
         'b0ea32b03eb8775d122c723a29e0db1e')

# 0.13 does not have a tag.
_relcommit="976f06ddf8d014fdfeee33a261e4f42eb4601e3b"
_relname="0.13"

pkgver() {
  cd "${_pkgname}"
  echo "${_relname}.$(git rev-list --count "${_relcommit}..HEAD").r$(git rev-parse --short HEAD)"
}

build() {
  cd "${_pkgname}"

  for f in {lua_strlen_fix}.patch; do
    msg2 "applying $f..."
    patch -p1 <"${srcdir}/$f"
  done

  msg2 "starting build..."

  [ -x configure ] || sh autogen.sh
  ./configure --prefix=/usr --mandir=/usr/share/man \
              --sysconfdir=/etc \
              --with-zlib \
              --without-lzma \
              --without-bzlib \
              --with-perl \
              --with-python \
              --enable-cgi \
              --enable-leds \
              --disable-smb \
              --enable-88-colors \
              --enable-256-colors \
              --enable-true-color \
              --enable-html-highlight \
              --enable-exmode
  export CPATH=/usr/include/python2.7
  export PYTHONPATH=/usr/bin/python2.7
  make
}

package() {
  cd "${_pkgname}"
  make DESTDIR="$pkgdir" install
  rm -f "$pkgdir/usr/share/locale/locale.alias"
}

# vim:set sw=2 sts=0 et:

```

**Comment by m040601** [comment]
@0lOI0lOI000I0l0IOIlOl0l0ll0IllI0l00OIO0 , thanks for your tips and hints

> Elinks, as of now, can only by compiled with python2.

By the way, do you know about this repo:

> rkd77/felinks: Fork of elinks 
> https://github.com/rkd77/felinks

They  seem to be dealing with python3 issues,  https://github.com/rkd77/felinks/issues/38


That repo gets updated very frequently and the name ""Witold Filipczyk" also appears in the log. Could it be some semi-official migration of elinks to github ? There a 0.13 realease in late 2019. That "official" elinks repo.or.cz domain is really odd.

**Comment by hellricer** [comment]
Hey, I'm currently using [this fork](https://github.com/yggi49/elinks) and all I needed was to instal python2 development libraries and run `./configure --with-python && make`.

The felinks looks really interesting, though!

**Comment by m040601** [comment]
> The felinks looks really interesting, though!

yes it does. Lots of recent commits to support python 3  
Felinks is actually the only "real elinks" as of 2020. The old elinks repo , repo.cz, that comes up in first google searches is abandoned since 2017.

Debian is building its officials packages frome felinks. Debian "elinks" official maintainer guy, also seems to be sending pull requests to felinks

```
Debian, https://tracker.debian.org/pkg/elinks  . 
 December 2019:
New upstream version 0.13.0 (cf6ac103) https://salsa.debian.org/aelmahmoudy-guest/elinks/commit/cf6ac10334a0f8c93f1c251d0fe6f8587c3df0b6
https://github.com/rkd77/felinks/pulls?q=is%3Apr+author%3Aaelmahmoudy
```

Confusingly, they still mark the "homepage" as http://elinks.cz

> I'm currently using this fork https://github.com/yggi49/elinks

That fork is basicly just pulling from felinks , last commit in early 2019, https://github.com/yggi49/elinks/commit/fd2c3255988061c1bdb061419ca5f9b4322d0311

Felinks is managed by someone who was an active contributer to the old elinks.. I guess he doesnt communicate that very well in english. He calls it a "fork of elinks", but by now felinks is an independent project.

I would be nice if one could had more recent hacks, tips, hooks and additions like soupmonkey to make felinks docs more up to date.
He seems willing, https://github.com/rkd77/felinks/issues/39

**Comment by m040601** [comment]
> .... all I needed was to instal python2 development libraries and run `./configure --with-python && make`.

Could you please list exactly the **python2 development libraries** you installed ? What is your system ? Debian ?

**Comment by hellricer** [comment]
I use Debian Testing and I the package is called `libpython2.7-dev` 

I wouldn't be so harsh about the fork vs "independent project" distinction, especially when it's only handful of commits ahead.

[Neovim](https://github.com/neovim/neovim), for example, has "vim-fork" in its description despite being drastically different nowadays...

**Comment by hellricer** [comment]
> That fork is basicly just pulling from felinks , last commit in early 2019, yggi49/elinks@fd2c325

It does't. The commit log of yggi49/elinks is identical to offical repo (https://repo.or.cz/elinks.git) except the last merge commit.

**Comment by hellricer** [comment]
> That fork is basicly just pulling from felinks , last commit in early 2019, yggi49/elinks@fd2c325

It's not. The log history is nearly identical to offical repo (https://repo.or.cz/elinks.git) except for the few commits. Felinks is about 150 commits ahead.

**Comment by hellricer** [comment]
Anyway, I pushed the changes that make it compatible with both python2 and python3 and it seems to run just fine in felinks.

For that I installed `libpython3.7-dev` package from Debian.
